trigger:
  branches:
    include:
    - v10/main
    - v10/develop
    - v10/release/*
    - v10/hotfix
  tags:
    include:
    - 10.*

pool:
  name: Default

variables: 
  BuildConfiguration: 'release'
  BuildPlatform: 'any cpu'
  Solution: '**\*.sln'
  NpmWorkingDirectory: 'src\Infocaster.Umbraco.DateFolders'

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build
    displayName: Build
    steps:
    - task: GitVersion@5
      displayName: GitVersion
      inputs:
        configFilePath: GitVersion.yml
        updateAssemblyInfo: true

    - task: UseDotNet@2
      displayName: 'Use .NET 6'
      inputs:
        packageType: 'sdk'
        version: '6.x'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: build
        projects: Infocaster.Umbraco.DateFolders.sln
        arguments: '--configuration $(BuildConfiguration) -p:Version=$(GitVersion.NuGetVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack'
      inputs:
        command: pack
        arguments: '--configuration $(BuildConfiguration) -p:Version=$(GitVersion.NuGetVersion)'
        packagesToPack: src/**/*.csproj
        versioningScheme: byEnvVar
        versionEnvVar: GitVersion.NuGetVersion

    - task: PublishBuildArtifacts@1
      displayName: 'Publish build artifacts'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: release
  displayName: Release
  dependsOn: build
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  variables:
    packageGlob: '$(Pipeline.Workspace)/**/Infocaster.Umbraco.DateFolders*.nupkg'
  jobs:
  - job: releaseArtifact
    displayName: Push to artifacts
    workspace:
      clean: all
    steps:
    - checkout: none
    
    - download: current
      patterns: '**/*.nupkg'
      displayName: Download build artifact
    
    - task: DotNetCoreCLI@2
      displayName: 'dotnet push'
      inputs:
        command: push
        publishVstsFeed: '3356baca-d7d8-497c-a5fa-ebd93f79f7c7'
        versioningScheme: byBuildNumber
        packagesToPush: $(packageGlob)

  - job: releaseNuget
    displayName: Push to nuget
    workspace:
      clean: all
    steps:
    - checkout: none
    
    - download: current
      patterns: '**/*.nupkg'
      displayName: Download build artifact
    
    - task: DotNetCoreCLI@2
      displayName: 'push to nuget.org'
      inputs:
        command: custom
        custom: nuget
        arguments: 'push $(packageGlob) -s https://api.nuget.org/v3/index.json --api-key $(NuGetApiKey)'