<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net472;net5.0</TargetFrameworks>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>Infocaster.Umbraco.NodeNameSync</PackageId>
		<Version>1.0.0</Version>
		<Title>Infocaster.NodeNameSync</Title>
		<Authors>Infocaster b.v.</Authors>
		<Company>Infocaster b.v.</Company>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Description>NodeNameSync for Umbraco</Description>
		<Copyright>Infocaster b.v. 2022</Copyright>

		<PackageProjectUrl>https://infocaster.net/wat-we-doen/umbraco-plugins/</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageIcon>infocaster_logo.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>infocaster nodenamesync umbraco</PackageTags>
		<RepositoryUrl>https://github.com/Infocaster/</RepositoryUrl>

		<Description>NodeNameSync for Umbraco</Description>
		<PackageReleaseNotes>1.0 - First version</PackageReleaseNotes>

		<ContentTargetFolders>.</ContentTargetFolders>

		<PackageOutputPath>../../output</PackageOutputPath>
		<IncludeBuildOutput>false</IncludeBuildOutput>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="App_Plugins\Infocaster.NodeNameSync\**\*.*">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
			<PackagePath>content\App_Plugins\Infocaster.NodeNameSync</PackagePath>
		</Content>
		<None Include="build\**\*.*">
			<Pack>True</Pack>
			<PackagePath>buildTransitive</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\infocaster_logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	
</Project>
