<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
		<PackageId>Infocaster.Umbraco.NodeNameSync</PackageId>
		<Version>10.0.0</Version>
		<Title>Infocaster.NodeNameSync</Title>
		<Authors>Infocaster b.v.</Authors>
		<Company>Infocaster b.v.</Company>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Copyright>Infocaster b.v. 2023</Copyright>

		<PackageProjectUrl>https://infocaster.net/wat-we-doen/umbraco-plugins/</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageIcon>infocaster_logo.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>infocaster nodenamesync umbraco contenteditor</PackageTags>
		<RepositoryUrl>https://github.com/Infocaster/</RepositoryUrl>

		<Description>NodeNameSync for Umbraco</Description>
		<PackageReleaseNotes>10.0.0 - V10 version with PropertyValueConverter</PackageReleaseNotes>

		<StaticWebAssetBasePath>App_Plugins/NodeNameSync</StaticWebAssetBasePath>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\infocaster_logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Umbraco.Cms.Core" Version="10.0.0" />
	</ItemGroup>
	
</Project>
